apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: redis
  source:
    chart: redis
    helm:
      version: v3
      parameters:
      - name: sentinel.enabled
        value: 'true'
      - name: replica.replicaCount
        value: '3'
      - name: sentinel.downAfterMilliseconds
        value: '1000'
      - name: sentinel.failoverTimeout
        value: '5000'
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.2.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
