apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: sonarqube
  source:
    chart: sonarqube
    repoURL: https://sonarsource.github.io/helm-chart-sonarqube
    targetRevision: 1.1.6+121
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
